import { blockSong } from "../api/backendApi";
import { useState } from "react";

export const Playlist = ({playlist}) => {
  const [name, setName] = useState("New playlist");
  const tracks = playlist?.tracks;

  const trackList = tracks?.map(track => {
    return (
      <li key={track.id}>
        {track.name}
        <button onClick={() => blockSong(track.id)}>block song</button>
      </li>
    );
  })
  return (
    <>
      {"This is the playlist page"}
      <ul>
        {trackList}
      </ul>
      Playlist name: <input onChange={(e) => setName(e.target.value)}/>
      <button onClick={() => createPlaylist({name}, "Generated by Threemix", tracks?.map(track => track.id)}>
        Export to Spotify
      </button>
    </>);
};
